# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestViewallpages():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_viewallpages(self):
    self.driver.get("http://localhost:3000/")
    self.driver.set_window_size(1522, 848)
    self.driver.find_element(By.CSS_SELECTOR, ".px-6:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".focus\\3A border-\\[\\#57321A\\]").click()
    self.driver.find_element(By.CSS_SELECTOR, ".focus\\3A border-\\[\\#57321A\\]").send_keys("prajaswadekar@gmail.com")
    self.driver.find_element(By.CSS_SELECTOR, ".block .flex:nth-child(2) > .w-full").click()
    self.driver.find_element(By.CSS_SELECTOR, ".block .flex:nth-child(2) > .w-full").send_keys("1234")
    self.driver.find_element(By.CSS_SELECTOR, ".w-full:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".sweep-button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".relative:nth-child(2) > .relative").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-\\[\\#EFC815\\]").click()
    self.driver.find_element(By.CSS_SELECTOR, ".relative:nth-child(3) > .relative").click()
    self.driver.find_element(By.CSS_SELECTOR, ".lucide-users").click()
    self.driver.find_element(By.CSS_SELECTOR, ".h-full:nth-child(1) > .bg-white > .p-4 > .w-full").click()
    self.driver.find_element(By.CSS_SELECTOR, ".lucide-x").click()
    self.driver.find_element(By.CSS_SELECTOR, ".relative:nth-child(4) > .relative").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".relative:nth-child(4) > .relative")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".lucide-log-out").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".border-b-2")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
  
